# adrestia-assertions/azure-pipelines.yml
# (c) 2020 Sam Caldwell.  See LICENSE.txt.
#
---
trigger:
  - master
  - development

jobs:
  - job: BuildTestLinux
    pool:
      vmImage: 'ubuntu-latest'
      timeoutInMinutes: 120
    steps:
      - checkout: self
        clean: true
        path: git

      - task: GoTool@0
        inputs:
          version: '1.14.2'

      - script: |
          ./githooks/pre-commit/linter
        displayName: Linter
        continueOnError: false
        enabled: true

      - script: |
          ./githooks/pre-push/run-tests
        displayName: Go tests
        continueOnError: false
        enabled: true

      - script: |
          ./scripts/static-analysis
        displayName: Static Analysis
        continueOnError: false
        enabled: true

      - script: |
          echo "Branch: $(Build.SourceBranchName)"
          echo "BuidId: $(Build.BuildId)"
        displayName: Current State
        continueOnError: false
        enabled: true
