# adrestia-assertions/azure-pipelines.yml
# (c) 2020 Sam Caldwell.  See LICENSE.txt.
#
---
trigger:
  - master
  - development

jobs:
  - job: BuildTestLinux
    pool:
      vmImage: 'ubuntu-latest'
      timeoutInMinutes: 120
    steps:
      - checkout: self
        # See BUILD_DIR.
        path: git

      - task: GoTool@0
        inputs:
          version: $(GO_VERSION)

      - script: |
          ./githooks/pre-commit/linter
          ./githooks/pre-push/run-tests
          ./scripts/static-analysis
        displayName: Run Golang tests.
        continueOnError: false
        enabled: true

      - script: |
          git tag -a "v$(Build.BuildId)" -m "release $(Build.BuildId)"
          git push origin --tags
        displayName: Tag and push
        continueOnError: false
        enabled: true
