# adrestia-assertions/azure-pipelines.yml
# (c) 2020 Sam Caldwell.  See LICENSE.txt.
#
---
trigger:
  - master
  - development

jobs:
  - job: BuildTestLinux
    pool:
      vmImage: 'ubuntu-latest'
      timeoutInMinutes: 120
    steps:
      - checkout: self
        clean: true
        path: git

      - task: GoTool@0
        inputs:
          version: '1.14.2'

      - script: |
          ./githooks/pre-commit/linter
          ./githooks/pre-push/run-tests
          ./scripts/static-analysis
        displayName: Run Golang tests.
        continueOnError: false
        enabled: true

  - job: Release
    pool:
      vmImage: 'ubuntu-latest'
      timeoutInMinutes: 120
    dependsOn: BuildTestLinux
    condition: and(succeeded(), eq(variables['SourceBranchName'], 'master'))
    steps:
      - script: |
          echo "Branch: $(Build.SourceBranchName)"
          echo "BuidId: $(Build.BuildId)"
          ./githooks/pre-commit/linter
          ./githooks/pre-push/run-tests
          ./scripts/static-analysis
        displayName: Run Golang tests.
        continueOnError: false
        enabled: true

      - task: GitHubRelease@1
        inputs:
          repositoryName: '$(Build.Repository.Name)'
          action: 'create'
          target: '$(Build.BuildId)'
          tagSource: 'gitTag'
          tagPattern: 'v*'
          assets:
          addChangeLog: false
