# adrestia-assertions/azure-pipelines.yml
# (c) 2020 Sam Caldwell.  See LICENSE.txt.
#
---
trigger:
  - master
  - development

jobs:
  - job: BuildTestLinux
    pool:
      vmImage: 'ubuntu-latest'
      timeoutInMinutes: 120
    steps:
      - checkout: self
        # See BUILD_DIR.
        path: git

      - task: GoTool@0
        inputs:
          version: '1.14.2'

      - script: |
          ./githooks/pre-commit/linter
          ./githooks/pre-push/run-tests
          ./scripts/static-analysis
        displayName: Run Golang tests.
        continueOnError: false
        enabled: true

      - script: |
          echo "Configure git"
          git config --global user.email "azure@samcaldwell.net"
          git config --global user.name "Azure Build Pipeline"
          echo "tag build on $(git branch | grep \* | head -n1)"
          echo "buildId: $(Build.BuildId)"
          [[ "$(git branch | grep \* | head -n1)" == "master" ]] && {
            git tag -a "v$(Build.BuildId)" -m "release $(Build.BuildId) "
            git push origin --tags
          }
        displayName: Tag and push
        continueOnError: false
        enabled: true
