# adrestia-assertions/azure-pipelines.yml
# (c) 2020 Sam Caldwell.  See LICENSE.txt.
#
---
trigger:
  - master
  - development

jobs:
  - job: BuildTestLinux
    pool:
      vmImage: 'ubuntu-latest'
      timeoutInMinutes: 120
      - checkout: self
        path: github.com/sam-caldwell/adrestia-assertions/pkg

      - task: GoTool@0
        inputs:
          version: '1.13.5'

      - script: ./scripts/build.sh
        displayName: Go Test
        enabled: true
        continueOnError: false
#
#  - job: BuildTestMacOs
#    pool:
#      vmImage: 'macOS-latest'
#      timeoutInMinutes: 120
#    steps:
#      - checkout: self
#        # See BUILD_DIR.
#        path: git
#
#      - script: go version
#        displayName: Go Version
#        continueOnError: false
#        enabled: true
#
#      - script: |
#          GOPATH=$GOPATH:$(pwd)
#          go test -v
#        displayName: Run Golang tests.
#        continueOnError: false
#        enabled: true
#
#  - job: BuildTestWindows
#    pool:
#      vmImage: 'windows-latest'
#      timeoutInMinutes: 120
#    steps:
#      - checkout: self
#        # See BUILD_DIR.
#        path: git
#
#      - script: go version
#        displayName: Go Version
#        continueOnError: false
#        enabled: true
#
#      - script: |
#          SET GOPATH=$GOPATH:$(pwd)
#          go test -v
#        displayName: Run Golang tests.
#        continueOnError: false
#        enabled: true

# ToDo: On successful builds, update tags for the given build.
#       Tag: <build>-release or <build>-development.
