# adrestia-assertions/azure-pipelines.yml
# (c) 2020 Sam Caldwell.  See LICENSE.txt.
#
---
trigger:
  - master
  - development

jobs:
  - job: BuildTestLinux
    pool:
      vmImage: 'ubuntu-latest'
      timeoutInMinutes: 120
    steps:
      - step:
          - checkout: self
            # See BUILD_DIR.
            path: git

      - task: GoTool@0
        inputs:
          version: '1.13.5'

      - task: Go@0
        inputs:
          command: 'get'
          arguments: '-d'
          workingDirectory: '$(System.DefaultWorkingDirectory)'

      - script: go version
        displayName: Go Version
        continueOnError: false
        enabled: true

      - script: |
          make lint
          make test
        displayName: Run Golang tests.
        continueOnError: false
        enabled: true
