# adrestia-assertions/azure-pipelines.yml
# (c) 2020 Sam Caldwell.  See LICENSE.txt.
#
---
trigger:
  - master
  - development

jobs:
  - job: BuildTestLinux
    strategy:
      matrix:
        GO_1_11:
          GO_VERSION: 1.11.13
        GO_1_12:
          GO_VERSION: 1.12.17
        GO_1_13:
          GO_VERSION: 1.13.9
        GO_1_14:
          GO_VERSION: 1.14
        GO_1_14_2:
          GO_VERSION: 1.14.2
      maxParallel: 2
    pool:
      vmImage: 'ubuntu-latest'
      timeoutInMinutes: 120
    steps:
      - checkout: self
        # See BUILD_DIR.
        path: git

      - task: GoTool@0
        inputs:
          version: $(GO_VERSION)

      - script: |
          ./githooks/pre-commit/linter
          ./githooks/pre-push/run-tests
          ./scripts/static-analysis
        displayName: Run Golang tests.
        continueOnError: false
        enabled: true

  - job: TagRelease
    pool:
      vmImage: 'ubuntu-latest'
      timeoutInMinutes: 120
      dependsOn: BuildTestLinux
      condition: |
        and(
          succeeded(),
          eq(
            variables['Build.SourceBranch'],
            'refs/heads/master'
        ))
      steps:
        - checkout: self
          path: git

        - scripts: |
            git tag -a "v$(Build.BuildId)" -m "release $(Build.BuildId)"
            git push origin --tags
          displayName: Tag and push
          enabled: true
