#!/bin/sh
# pre-push git hook
# (c) 2020 Sam Caldwell.  See LICENSE.txt
#
# This ensures `make lint` runs and passes before we push.
command -v yamllint -v || brew install yamllint

for f in $(find ./ -name "*.y*ml" -type f); do
    yamllint "$f" ||{
        echo "Lint $f fails"
        exit 1
     }
    echo "Lint $f passes"
done

golint || go get -u golang.org/x/lint/golint

golint -set_exit_status
[[ "$?" == "0" ]] && {
    echo "golint passes"
    exit 0
}
echo "golint failed."
exit 1

